ASSETS_FOLDER_PATH = '../assets'

MAP_WIDTH_IN_TILES = 16
MAP_HEIGHT_IN_TILES = 16

UNIT_IN_PX = 24

MAP_WIDTH_IN_PX = MAP_WIDTH_IN_TILES * UNIT_IN_PX
MAP_HEIGHT_IN_PX = MAP_HEIGHT_IN_TILES * UNIT_IN_PX

GAME_LOOP_INTERVAL = 100
