ASSETS_FOLDER_PATH = '../assets'

MAP_WIDTH_IN_TILES = 16
MAP_HEIGHT_IN_TILES = 16

UNIT_IN_PX = 36
TILE_IN_PX = 36

GAME_LOOP_INTERVAL_TICK = 10
GAME_LOOP_INTERVAL_IN_TICKS = 25
GAME_LOOP_INTERVAL = GAME_LOOP_INTERVAL_TICK * GAME_LOOP_INTERVAL_IN_TICKS

MAP_WIDTH_IN_PX = MAP_WIDTH_IN_TILES * UNIT_IN_PX
MAP_HEIGHT_IN_PX = MAP_HEIGHT_IN_TILES * UNIT_IN_PX

MOVE_PX_PER_TICK = UNIT_IN_PX / GAME_LOOP_INTERVAL_IN_TICKS
